services:
  db:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432

  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres_data:
